### ISSUE TITLE
Pick correct names of clients as defined in Router LAN DHCP Server

### ISSUE THREAD

**Issue by gspannu** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#141]
**Enhancement/ Feature Request:**

Adguard Home picks up the client names automatically from the router and displays the same in its GUI.
_However, the names are what are reported by dnsmasq rather than what have been defined in the DHCP server._

Feature Request:
Is there any way for Adguard Home to **use the client names** from the 'defined names as listed in LAN DHCP server'

To highlight the difference
**Static IPs defined in the router DHCP page (LAN - DHCP Server)**

<img width="764" alt="Screenshot 1" src="https://user-images.githubusercontent.com/137664/157440066-fe6cfbf9-fc62-4cd9-844a-2d9b2ecb1467.png">
<img width="759" alt="Screenshot 2" src="https://user-images.githubusercontent.com/137664/157440095-536121ba-caf2-41d3-8b72-c3ffa3f6ec59.png">

**Client names as seen in Adguard Home**

<img width="907" alt="Screenshot" src="https://user-images.githubusercontent.com/137664/157440123-614f793a-facb-41c5-9a25-99a87730aeb6.png">

### Q: Can Adguard Home pick up the names from the defined DHCP server?
_A way maybe to add the DHCP names to etc/hosts file at runtime; as AGH does use the etc/hosts file to display the correct names._

**Comment by jumpsmm7** [comment]
You have to turn off arp requesting if you want adguardhome to rely solely on your /etc/hosts. This is an AdGuardHome itself issue on choosing whether it prefers ARP names before /etc/hosts, I suggest you open a feature request with AdGuardHome devs themselves, not here on the installers issue tracker.

**Comment by jumpsmm7** [comment]
What you are asking for the installer to be able to do is not really practical or viable, since the router DHCP list has a size limit and not all client Names remain agnostic. This would me every client would need a static reservation on your router as well. I hope you can see this is an AdGuardHome feature request, and not one that should be expected of from this installer.

**Comment by jumpsmm7** [comment]
If you were properly identifying client names from /etc/hosts or dnsmasq, you would see "/etc/hosts" or "rdns" as the source from which the clients were identified.

**Comment by jumpsmm7** [comment]
The problem with the dhcp page is that if it is not appending to /etc/hosts, then it wont get preference over what arps are being read. If you want those clients to be read you should append them to /etc/hosts with /jffs/configs/host.add.

**Comment by jumpsmm7** [comment]
Alternatively you could try appending **localise-queries** to /jffs/configs/dnsmasq.conf.add , I am not promising this will solve it 100% but dnsmasq says 
Return answers to DNS queries from /etc/hosts and --interface-name and --dynamic-host which depend on the interface over which the query was received. If a name has more than one address associated with it, and at least one of those addresses is on the same subnet as the interface to which the query was sent, then return only the address(es) on that subnet. This allows for a server to have multiple addresses in /etc/hosts corresponding to each of its interfaces, and hosts will get the correct address based on which network they are attached to. Currently this facility is limited to IPv4.

**Comment by jumpsmm7** [comment]
Alternatively, you can define a host name on the DHCP page,  which I do, and it works. ( i recommend copying the name from client name part, and list it as the host name.)

**Comment by jumpsmm7** [comment]
example
![image](https://user-images.githubusercontent.com/49514613/157865309-915ca579-5801-40ba-88de-204a726bcfd8.png)

**Comment by gspannu** [comment]
> Alternatively, you can define a host name on the DHCP page, which I do, and it works. ( i recommend copying the name from client name part, and list it as the host name.)

I think this may be the simplest option.... I will give this a go.

**Wonder, why I didn't think of this before - stupid me !!!**
