### ISSUE TITLE
Can't complete installation

### ISSUE THREAD

**Issue by Cliffback** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#156]
I SSH'ed into the router, which get's me to this folder: /tmp/home/root#

I'm running the latest Merlin release.

When I run the configuration, I can't get past an error saying that it was unable to create the folders needed. 

Is there something more I need to do on beforehand to get into the router correctly?

![image](https://user-images.githubusercontent.com/51080320/166932356-31aa5e37-a167-41c8-b188-c5510927901d.png)

EDIT: figured I needed to go through amtm to install it from there, got it working now

**Comment by jumpsmm7** [comment]
> I SSH'ed into the router, which get's me to this folder: /tmp/home/root#
> 
> I'm running the latest Merlin release.
> 
> When I run the configuration, I can't get past an error saying that it was unable to create the folders needed.
> 
> Is there something more I need to do on beforehand to get into the router correctly?
> 
> ![image](https://user-images.githubusercontent.com/51080320/166932356-31aa5e37-a167-41c8-b188-c5510927901d.png)
> 
> EDIT: figured I needed to go through amtm to install it from there, got it working now

It isn't an error, something is either wrong with your Entware directory path or you don't have entware installed, which is one of the requirements.
