### ISSUE TITLE
Error please contact DEV

### ISSUE THREAD

**Issue by foxy999** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#178]
Hi there, can't seem to get this to be installed can you help ?
<img width="337" alt="image" src="https://user-images.githubusercontent.com/7655564/188477423-ba19330b-70f9-4938-abf5-cc6442a47aae.png">

**Comment by jumpsmm7** [comment]
The opkg not found error means that when you were trying to reconfigure, there was an issue with your entware repository. You probably need to update and upgrade your entware repository. This can be done using AMTM. I first recommend rebooting your computer before attempting to update and upgrade entware. 

`opkg update && opkg upgrade`

is what you would type in the terminal.

**Comment by gspannu** [comment]
> Screenshot_20220906-112215_JuiceSSH
> This will show you how to upgrade entware via amtm menu.

Quick question:
What ssh client are you using?
What is the OS in the screenshot?

**Comment by foxy999** [comment]
> 

Hey Thanks for your reply and sorry for the delay, indeed i have to install Entware and thus have a USB key on the router, but i ran out of USB Ports so i'll just leave it for for now thanks.

**Comment by jumpsmm7** [comment]
> > Screenshot_20220906-112215_JuiceSSH
> > This will show you how to upgrade entware via amtm menu.
> 
> Quick question: What ssh client are you using? What is the OS in the screenshot?

Juice from the Google play store. It is an android os.
