### ISSUE TITLE
Python error during install on Asus RT-AX86U Pro

### ISSUE THREAD

**Issue by Smokey613** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#187]
I have ran AdGuardHome in the past on my RT-AC86U and it ran perfectly.

My new RT-AX86U Pro on the otherhand does not like it. No matter what I try I continue to have the missing python error and I cannot login to the admin web interface.

I get this error during install.

/opt/etc/AdGuardHome/installer: line 1112: python: not found

**Comment by jumpsmm7** [comment]
Possible solution already discussed here, try this:

https://www.snbforums.com/threads/asuswrt-merlin-adguardhome-installer-amaghi-cont.79862/post-836171

and please report back your findings.
