### ISSUE TITLE
Port 3000 not 14711

### ISSUE THREAD

**Issue by drejjmit** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#188]
Took me forever to figure this out. Maybe you should update the notification 
```
AdGuard Home is available on the following addresses:
Go to http://127.0.0.1:3000
Go to http://X.X.X.X:3000
```
https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started

**Comment by jumpsmm7** [comment]
> In my test it is       PTXT "$INFO ADGUARDHOME_VER=$($AGH_FILE --version | cut -d" "  -f4-)" \
           "$INFO Run Option 1 to upgrade or change builds." \
           "$INFO To visit AdGuardHome," \
           "$INFO please go to http://$(nvram get lan_ipaddr):14711 ." \
           "$INFO You can use the WebUI to change things to your liking!" \
	   "$INFO Stop by https://github.com/AdguardTeam/AdGuardHome/wiki " \
	   "$INFO for any configuration needs. "

**Comment by jumpsmm7** [comment]
> Of course i did not change the bind port on my own and then came here to tell you xD Somewhere it's set to 3000. Not sure if it's your script or the AdGuard installer that sets it to 3000 ![image](https://user-images.githubusercontent.com/15526476/240842726-b8372947-5bec-479d-ac64-9ea636b8f16e.png)

Did you copy an old .yaml file from a different configuration? I just installed using the installer and my bind port is set properly.

**Comment by jumpsmm7** [comment]
Here is my install method:
![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/e9352347-2ce8-4dbb-8c81-cfeb9ff318fa)
![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/1a28f3f6-a71c-4b97-bd2d-6d1976d3dac0)
![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/84ec90ae-d42c-42d4-b480-4b6330f4494f)
![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/424623c6-61b1-4175-8407-133f06e3ef47)
![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/39c754ba-3461-4614-98e3-de2d17ce9dcf)
![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/df439a4e-a32d-4203-8fef-19ff5d156919)
![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/27ab2e75-1929-4bc9-b62b-4148c72455de)

**Comment by drejjmit** [comment]
Here's a copy of the log when I installed

![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/15526476/b23bd113-575b-40f5-86b9-41dc617d4000)

**Comment by jumpsmm7** [comment]
> Here's a copy of the log when I installed
> 
> ![image](https://user-images.githubusercontent.com/15526476/241078477-b23bd113-575b-40f5-86b9-41dc617d4000.png)

Yea there is definitely something wrong, or not right ,about your setup. For starters, there are errors trying to create the necessary files in /jffs/scripts

![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/19f23e1f-75cf-42df-aa15-4a94818000bd)

Entware is not letting you set the username and password in the terminal, or install the column package:

![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/49514613/644eb386-2716-41d7-bb30-e4453fde75d1)

To me, this indicates a problem specific to your setup with `/jffs/scripts/`. Your Entware is not working properly (it is possibly corrupt or on a corrupt USB). ALL of this is indicated from the errors presented from your terminal session.

**Comment by jumpsmm7** [comment]
> > Here's a copy of the log when I installed
> > ![image](https://user-images.githubusercontent.com/15526476/241078477-b23bd113-575b-40f5-86b9-41dc617d4000.png)
> 
> Yea there is definitely something wrong, or not right ,about your setup. For starters, there are errors trying to create the necessary files in /jffs/scripts
> 
> ![image](https://user-images.githubusercontent.com/49514613/241080722-19f23e1f-75cf-42df-aa15-4a94818000bd.png)
> 
> Entware is not letting you set the username and password in the terminal, or install the column package:
> 
> ![image](https://user-images.githubusercontent.com/49514613/241080871-644eb386-2716-41d7-bb30-e4453fde75d1.png)
> 
> To me, this indicates a problem specific to your setup with `/jffs/scripts/`. Your Entware is not working properly (it is possibly corrupt or on a corrupt USB). ALL of this is indicated from the errors presented from your terminal session.

In order for AdGuardHome to install and work properly using this installer, Your USB must be in tip top shape, and /jffs/scripts and entware must be fully functional.
