### ISSUE TITLE
Unable to install via AMTM on ASUS RT-N18U

### ISSUE THREAD

**Issue by djrooli** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#190]
After Merlin firmware update I was not able to update or install AG anymore.

![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/50361400/00b85989-a543-421a-bb1f-b94dbb201a69)

This is an update attempt on the pic, but it is not installed actually.
Before, the error message was "Illegal operation".

This is an USB3.0 ext2 SSD 512gb.

Thank you.

**Comment by jumpsmm7** [comment]
These are the Supported Models for Asuswrt-Merlin firmware

**Comment by djrooli** [comment]
Thank you for your answer.

I have installed this on this router, not on different one.
As you said there's no support for this model, os any update could
have made this stop working, but very strange...this fork offers AG
and this is made especially for my model.

I planned to replace the router anyways, so It seems I can't avoid.
