### ISSUE TITLE
Consider downloading binary from github 

### ISSUE THREAD

**Issue by giwty** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#2]
Not really an issue, but just a quick feedback that i was not able to install it yesterday because the download from "https://static.adguard.com/adguardhome/release/" was super slow and kept breaking, resulting in corrupted tar file.
Using wget instead of cURL helped, as it will resume the download when it reset. (you can probably do the same with cURL).

If it's all the same, might want to consider set the download from github instead.

Other then that, great installer, thanks for your work

**Comment by jumpsmm7** [comment]
> Not really an issue, but just a quick feedback that i was not able to install it yesterday because the download from "https://static.adguard.com/adguardhome/release/" was super slow and kept breaking, resulting in corrupted tar file. Using wget instead of cURL helped, as it will resume the download when it reset. (you can probably do the same with cURL).
> 
> If it's all the same, might want to consider set the download from github instead.
> 
> Other then that, great installer, thanks for your work

That is their github address and I don't have issues with cURL so I won't be addressing this as an issue. Thanks for the feedback. My feedback would be to you that if you cannot get cURL to work then you might have bigger issues on your router that you need to address.
