### ISSUE TITLE
fatal error: runtime: cannot allocate memory when starting installer script

### ISSUE THREAD

**Issue by nerdinary** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#216]
I already have AdGuard installed and running. I wanted to run the script to see if there are any updates. Here is what I get:

```
> curl -L -s -k -O https://raw.githubusercontent.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/master/insta
ller
> sh installer

 Info:  Detected RT-AX88U router.
 Info:  Detected Linux platform.
 Info:  Detected ARMv8 architecture.
 Info:  JFFS custom scripts and configs are already enabled.
 Info:  DNS Environment is Ready.
 Info:  New AI_VERSION=v1.7.4 Available!
 Info:  Run Option 1 of the Installer to upgrade Asuswrt-Merlin-AdGuardHome-Installer.
fatal error: runtime: cannot allocate memory

<snip>
...
```

I've attached the stacktrace that follows

[stacktrace_merlin_adguard.txt](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/files/14392465/stacktrace_merlin_adguard.txt)

**Comment by jumpsmm7** [comment]
> I already have AdGuard installed and running. I wanted to run the script to see if there are any updates. Here is what I get:
> 
> ```
> > curl -L -s -k -O https://raw.githubusercontent.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/master/insta
> ller
> > sh installer
> 
>  Info:  Detected RT-AX88U router.
>  Info:  Detected Linux platform.
>  Info:  Detected ARMv8 architecture.
>  Info:  JFFS custom scripts and configs are already enabled.
>  Info:  DNS Environment is Ready.
>  Info:  New AI_VERSION=v1.7.4 Available!
>  Info:  Run Option 1 of the Installer to upgrade Asuswrt-Merlin-AdGuardHome-Installer.
> fatal error: runtime: cannot allocate memory
> 
> <snip>
> ...
> ```
> 
> I've attached the stacktrace that follows
> 
> [stacktrace_merlin_adguard.txt](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/files/14392465/stacktrace_merlin_adguard.txt)

This is an indication that your router is out of memory. I wish there was more I can do to help with this matter, but there isn't. Especially if you are doing everything you already can which includes using only the default adguardhome blocklists, have a reasonable size swap, and do not have too many scripts causing additional background load on the router.
