### ISSUE TITLE
Log location doesn't work, still writes to syslog

### ISSUE THREAD

**Issue by khadanja** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#218]
Set location here, can see logs in router gui. Not creating log file at the specified location. 
log:
  file: /mnt/Asus/entware/etc/AdGuardHome/AdGuardHome.log
  max_backups: 0
  max_size: 100
  max_age: 3
  compress: false
  local_time: false
  verbose: true

**Comment by jumpsmm7** [comment]
> Set location here, can see logs in router gui. Not creating log file at the specified location. log: file: /mnt/Asus/entware/etc/AdGuardHome/AdGuardHome.log max_backups: 0 max_size: 100 max_age: 3 compress: false local_time: false verbose: true

That is because the log location is being specified inside the init.d script - "/opt/etc/init.d/S99AdGuardHome". You need to change the "syslog" to the actual location of your logfile, then it will work i.e. "/opt/etc/AdGuardHome/AdGuardHome.log".
