### ISSUE TITLE
AdGuard dead

### ISSUE THREAD

**Issue by totoro1822** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#219]
Hello, my AdGuard is not working anymore (status is "dead" and GUI is not accessible). Reinstall didn't help.

I am running MerlinWRT 3004.388.8_2 on a GT-AX6000. Required directories and files are attached.

Thank you.

[AdGuardHome.zip](https://github.com/user-attachments/files/17561404/AdGuardHome.zip)

**Comment by jumpsmm7** [comment]
@totoro1822 
You have a corrupt .yaml file. I don't know why your file is becoming corrupt, but here is what it looks like on the inside. 

> http:
  address: 0.0.0.0:65535
users:
- name: totorouter
  password: REDACTED
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  upstream_dns:
  - '[/router.asus.com/][::]:553'
  - '[/www.asusnetwork.net/][::]:553'
  - '[/www.asusrouter.com/][::]:553'
  - '[/use-application-dns.net/][::]:553'
  - '[/dns.resolver.arpa/][::]:553'
  - '[/lan/][::]:553'
  - '[//][::]:553'
  - [A[B
  - 8.8.8.8
  - tcp://[A[B
  - tcp://8.8.8.8
  bootstrap_dns:
  - [A[B
  - 8.8.8.8
  fallback_dns:
  - [A[B
  - 8.8.8.8
  - tcp://[A[B
  - tcp://8.8.8.8
  resolve_clients: true
  use_private_ptr_resolvers: true
  local_ptr_upstreams:
  - '[::]:553'
  - '[/10.in-addr.arpa/][::]:553'
  - '[/168.192.in-addr.arpa/][::]:553'
schema_version: 29

**Comment by totoro1822** [comment]
Thank you for your feedback?

How can I solve the issue?

I tried the "reconfigure" option but I get this error, after which internet connection wasn't working anymore and I had to uninstall AdGuard

AdGuardHome configuration...
2024/10/29 22:58:03 [error] Couldn't get logging settings from the configuration: yaml: control characters are not allowed
 Info:  Moving invalid configuration file to /opt/etc/AdGuardHome/AdGuardHome.yaml.err.
 Info:  Operation will continue with clean config file.
 *** Error:  Writing AdGuardHome configuration failed 
 *** Error:  Please send /opt/etc/AdGuardHome/AdGuardHome.yaml.err file and screen log of 
 *** Error:  all ssh terminal operations to the script developer.
 Info:  Operation completed, returning to Main Menu. You can quit or continue.
=====================================================

**Comment by jumpsmm7** [comment]
> @jumpsmm7 Thank you for your feedback.
> 
> How can I solve the issue?
> 
> I tried the "reconfigure" option but I get this error, after which internet connection wasn't working anymore and I had to uninstall AdGuard
> 
> # AdGuardHome configuration...
> 2024/10/29 22:58:03 [error] Couldn't get logging settings from the configuration: yaml: control characters are not allowed
> Info: Moving invalid configuration file to /opt/etc/AdGuardHome/AdGuardHome.yaml.err.
> Info: Operation will continue with clean config file.
> *** Error: Writing AdGuardHome configuration failed
> *** Error: Please send /opt/etc/AdGuardHome/AdGuardHome.yaml.err file and screen log of
> *** Error: all ssh terminal operations to the script developer.
> Info: Operation completed, returning to Main Menu. You can quit or continue.

What build version of adguardhome are you choosing for the install?

**Comment by jumpsmm7** [comment]
@totoro1822 if you need to manually uninstall this for a reinstall to be successful, here is how to manually uninstall it. 
https://www.snbforums.com/threads/adguardhome-new-releases-2023.85191/post-848419
follow the directions in this post.

**Comment by totoro1822** [comment]
Solved after manual uninstall, thank you

**Comment by francoism90** [comment]
@jumpsmm7 I'm unable to install the newest release, is this related?

It downloads the new version, but it keeps using the previous one.
