### ISSUE TITLE
deteached no internet error

### ISSUE THREAD

**Issue by 376375160** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#61]
Hello, I used your script yesterday, and the previous conditions are met. When I choose 1 and start the installation, I am prompted that I have not detected the network connection. What is the reason

**Comment by jumpsmm7** [comment]
You are going to need to be more specific then that, there is a good chance your internet connection was failing to connect to the servers.

**Comment by 376375160** [comment]
Thank you for your reply. I read the reason for the error yesterday. There should be no problem with DNS setting, otherwise I can't surf the Internet through the router. In fact, I can surf the Internet through the router. Then I looked at the source code of your script. The error is probably in line 140, which is exactly the two-step check you said. There is no problem with Ping check. NSLOOKUP Google COM 127.0.0.1 I'm not sure what this code means. Could you please explain it, thank you

**Comment by 376375160** [comment]
In addition, I would like to ask whether my router firmware is based on Merlin secondary packaging. Can this type of firmware be supported, or do I have to use the original Merlin firmware?

**Comment by jumpsmm7** [comment]
> In addition, I would like to ask whether my router firmware is based on Merlin secondary packaging. Can this type of firmware be supported, or do I have to use the original Merlin firmware?

I don't know of a "Merlin secondary packaging". It is only intended for Asus routers running Asuswrt-Merlin. I am not able to provide support for any other routers than such. 



> Thank you for your reply. I read the reason for the error yesterday. There should be no problem with DNS setting, otherwise I can't surf the Internet through the router. In fact, I can surf the Internet through the router. Then I looked at the source code of your script. The error is probably in line 140, which is exactly the two-step check you said. There is no problem with Ping check. NSLOOKUP Google COM 127.0.0.1 I'm not sure what this code means. Could you please explain it, thank you

The check is seeing if your DNS connection is working. If it isn't, then obviously you wouldn't be able to properly download anything on the router itself. 127.0.0.1 is just a generic loop back address that dnsmasq ( and AdGuardHome once it is installed) listens on. Dnsmasq listens on all addresses 0.0.0.0. so the check is valid, if you are failing, then there is a miss configuration somewhere on your router.
